//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.30 at 12:44:24 AM BST 
//


package com.student.soap.contract;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.student.soap.contract package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.student.soap.contract
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SoapNamedObjectsResponse }
     * 
     */
    public SoapNamedObjectsResponse createSoapNamedObjectsResponse() {
        return new SoapNamedObjectsResponse();
    }

    /**
     * Create an instance of {@link SoapCarModelsResponse }
     * 
     */
    public SoapCarModelsResponse createSoapCarModelsResponse() {
        return new SoapCarModelsResponse();
    }

    /**
     * Create an instance of {@link SoapCarModelsResponse.CarModels }
     * 
     */
    public SoapCarModelsResponse.CarModels createSoapCarModelsResponseCarModels() {
        return new SoapCarModelsResponse.CarModels();
    }

    /**
     * Create an instance of {@link SoapNamedObjectsResponse.NamedObjects }
     * 
     */
    public SoapNamedObjectsResponse.NamedObjects createSoapNamedObjectsResponseNamedObjects() {
        return new SoapNamedObjectsResponse.NamedObjects();
    }

    /**
     * Create an instance of {@link SoapResponse }
     * 
     */
    public SoapResponse createSoapResponse() {
        return new SoapResponse();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link SoapTransmissionTypesRequest }
     * 
     */
    public SoapTransmissionTypesRequest createSoapTransmissionTypesRequest() {
        return new SoapTransmissionTypesRequest();
    }

    /**
     * Create an instance of {@link SoapCarModelsByManufacturerRequest }
     * 
     */
    public SoapCarModelsByManufacturerRequest createSoapCarModelsByManufacturerRequest() {
        return new SoapCarModelsByManufacturerRequest();
    }

    /**
     * Create an instance of {@link SoapCarManufacturersRequest }
     * 
     */
    public SoapCarManufacturersRequest createSoapCarManufacturersRequest() {
        return new SoapCarManufacturersRequest();
    }

    /**
     * Create an instance of {@link SoapCarRequest }
     * 
     */
    public SoapCarRequest createSoapCarRequest() {
        return new SoapCarRequest();
    }

    /**
     * Create an instance of {@link SoapAllCarModelsRequest }
     * 
     */
    public SoapAllCarModelsRequest createSoapAllCarModelsRequest() {
        return new SoapAllCarModelsRequest();
    }

    /**
     * Create an instance of {@link SoapFuelTypesRequest }
     * 
     */
    public SoapFuelTypesRequest createSoapFuelTypesRequest() {
        return new SoapFuelTypesRequest();
    }

    /**
     * Create an instance of {@link SoapCarResponse }
     * 
     */
    public SoapCarResponse createSoapCarResponse() {
        return new SoapCarResponse();
    }

    /**
     * Create an instance of {@link SoapCarClassesRequest }
     * 
     */
    public SoapCarClassesRequest createSoapCarClassesRequest() {
        return new SoapCarClassesRequest();
    }

    /**
     * Create an instance of {@link SoapCarModelsResponse.CarModels.CarModel }
     * 
     */
    public SoapCarModelsResponse.CarModels.CarModel createSoapCarModelsResponseCarModelsCarModel() {
        return new SoapCarModelsResponse.CarModels.CarModel();
    }

    /**
     * Create an instance of {@link SoapNamedObjectsResponse.NamedObjects.NamedObject }
     * 
     */
    public SoapNamedObjectsResponse.NamedObjects.NamedObject createSoapNamedObjectsResponseNamedObjectsNamedObject() {
        return new SoapNamedObjectsResponse.NamedObjects.NamedObject();
    }

}
