//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.29 at 11:32:18 PM BST 
//


package com.student.soap.contract;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.student.com/soap/contract}StatusType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="modelId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="modelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="manufacturerId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="manufacturerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fuelTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="fuelTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transmissionId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="transmissionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carClassId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="carClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mileage" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="mileageThreshold" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="mileagePenalty" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="collisionWaranty" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="totalPrice" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="childSeats" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="publisherId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="publisherName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="publisherTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="publisherTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}integer" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "modelId",
    "modelName",
    "manufacturerId",
    "manufacturerName",
    "fuelTypeId",
    "fuelTypeName",
    "transmissionId",
    "transmissionName",
    "carClassId",
    "carClassName",
    "mileage",
    "mileageThreshold",
    "mileagePenalty",
    "collisionWaranty",
    "price",
    "discount",
    "totalPrice",
    "childSeats",
    "rating",
    "publisherId",
    "publisherName",
    "publisherTypeId",
    "publisherTypeName",
    "image"
})
@XmlRootElement(name = "soapCarResponse")
public class SoapCarResponse
    extends StatusType
{

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(required = true)
    protected BigInteger modelId;
    @XmlElement(required = true)
    protected String modelName;
    @XmlElement(required = true)
    protected BigInteger manufacturerId;
    @XmlElement(required = true)
    protected String manufacturerName;
    @XmlElement(required = true)
    protected BigInteger fuelTypeId;
    @XmlElement(required = true)
    protected String fuelTypeName;
    @XmlElement(required = true)
    protected BigInteger transmissionId;
    @XmlElement(required = true)
    protected String transmissionName;
    @XmlElement(required = true)
    protected BigInteger carClassId;
    @XmlElement(required = true)
    protected String carClassName;
    @XmlElement(required = true)
    protected BigInteger mileage;
    @XmlElement(required = true)
    protected BigInteger mileageThreshold;
    @XmlElement(required = true)
    protected BigInteger mileagePenalty;
    @XmlElement(required = true)
    protected BigInteger collisionWaranty;
    @XmlElement(required = true)
    protected BigInteger price;
    @XmlElement(required = true)
    protected BigInteger discount;
    @XmlElement(required = true)
    protected BigInteger totalPrice;
    @XmlElement(required = true)
    protected BigInteger childSeats;
    @XmlElement(required = true)
    protected BigInteger rating;
    @XmlElement(required = true)
    protected BigInteger publisherId;
    @XmlElement(required = true)
    protected String publisherName;
    @XmlElement(required = true)
    protected BigInteger publisherTypeId;
    @XmlElement(required = true)
    protected String publisherTypeName;
    protected List<BigInteger> image;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the modelId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getModelId() {
        return modelId;
    }

    /**
     * Sets the value of the modelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setModelId(BigInteger value) {
        this.modelId = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the manufacturerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getManufacturerId() {
        return manufacturerId;
    }

    /**
     * Sets the value of the manufacturerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setManufacturerId(BigInteger value) {
        this.manufacturerId = value;
    }

    /**
     * Gets the value of the manufacturerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerName() {
        return manufacturerName;
    }

    /**
     * Sets the value of the manufacturerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerName(String value) {
        this.manufacturerName = value;
    }

    /**
     * Gets the value of the fuelTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFuelTypeId() {
        return fuelTypeId;
    }

    /**
     * Sets the value of the fuelTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFuelTypeId(BigInteger value) {
        this.fuelTypeId = value;
    }

    /**
     * Gets the value of the fuelTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuelTypeName() {
        return fuelTypeName;
    }

    /**
     * Sets the value of the fuelTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuelTypeName(String value) {
        this.fuelTypeName = value;
    }

    /**
     * Gets the value of the transmissionId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTransmissionId() {
        return transmissionId;
    }

    /**
     * Sets the value of the transmissionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTransmissionId(BigInteger value) {
        this.transmissionId = value;
    }

    /**
     * Gets the value of the transmissionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransmissionName() {
        return transmissionName;
    }

    /**
     * Sets the value of the transmissionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransmissionName(String value) {
        this.transmissionName = value;
    }

    /**
     * Gets the value of the carClassId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCarClassId() {
        return carClassId;
    }

    /**
     * Sets the value of the carClassId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCarClassId(BigInteger value) {
        this.carClassId = value;
    }

    /**
     * Gets the value of the carClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarClassName() {
        return carClassName;
    }

    /**
     * Sets the value of the carClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarClassName(String value) {
        this.carClassName = value;
    }

    /**
     * Gets the value of the mileage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMileage() {
        return mileage;
    }

    /**
     * Sets the value of the mileage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMileage(BigInteger value) {
        this.mileage = value;
    }

    /**
     * Gets the value of the mileageThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMileageThreshold() {
        return mileageThreshold;
    }

    /**
     * Sets the value of the mileageThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMileageThreshold(BigInteger value) {
        this.mileageThreshold = value;
    }

    /**
     * Gets the value of the mileagePenalty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMileagePenalty() {
        return mileagePenalty;
    }

    /**
     * Sets the value of the mileagePenalty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMileagePenalty(BigInteger value) {
        this.mileagePenalty = value;
    }

    /**
     * Gets the value of the collisionWaranty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCollisionWaranty() {
        return collisionWaranty;
    }

    /**
     * Sets the value of the collisionWaranty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCollisionWaranty(BigInteger value) {
        this.collisionWaranty = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrice(BigInteger value) {
        this.price = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDiscount(BigInteger value) {
        this.discount = value;
    }

    /**
     * Gets the value of the totalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the value of the totalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalPrice(BigInteger value) {
        this.totalPrice = value;
    }

    /**
     * Gets the value of the childSeats property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChildSeats() {
        return childSeats;
    }

    /**
     * Sets the value of the childSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChildSeats(BigInteger value) {
        this.childSeats = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRating(BigInteger value) {
        this.rating = value;
    }

    /**
     * Gets the value of the publisherId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPublisherId() {
        return publisherId;
    }

    /**
     * Sets the value of the publisherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPublisherId(BigInteger value) {
        this.publisherId = value;
    }

    /**
     * Gets the value of the publisherName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublisherName() {
        return publisherName;
    }

    /**
     * Sets the value of the publisherName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublisherName(String value) {
        this.publisherName = value;
    }

    /**
     * Gets the value of the publisherTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPublisherTypeId() {
        return publisherTypeId;
    }

    /**
     * Sets the value of the publisherTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPublisherTypeId(BigInteger value) {
        this.publisherTypeId = value;
    }

    /**
     * Gets the value of the publisherTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublisherTypeName() {
        return publisherTypeName;
    }

    /**
     * Sets the value of the publisherTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublisherTypeName(String value) {
        this.publisherTypeName = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the image property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getImage() {
        if (image == null) {
            image = new ArrayList<BigInteger>();
        }
        return this.image;
    }

}
