//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
// Generated on: 2020.06.04 at 07:13:09 PM CEST 
=======
// Generated on: 2020.06.03 at 06:41:13 PM CEST 
>>>>>>> 90ae7a7f0050ecc99b4b2d909c7a43c5b16043ab
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.student.com/agentservice/soap/contract", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.student.soap.agentservice.contract;
