version: '3'

services:

    AgentService:
        build: ./AgentService
        image: agentser
        container_name: agentser
        restart: on-failure
        ports:
            - "8083:80"
        environment:
            LOG_STORAGE: /var/log/web-traffic.log
        volumes:
            - logs:/var/log
      
    CarService:
        build: ./CarService
        image: carser
        container_name: carser
        restart: on-failure
        ports:
            - "8082:80"
        environment:
            LOG_STORAGE: /var/log/web-traffic.log
        volumes:
            - logs:/var/log
    
    ScheduleService:
        build: ./ScheduleService
        image: schser
        container_name: schser
        restart: on-failure
        ports:
            - "8084:80"
        environment:
            LOG_STORAGE: /var/log/web-traffic.log
        volumes:
            - logs:/var/log
    
    UserService:
        build: ./UserService
        image: useser
        container_name: useser
        restart: on-failure
        ports:
            - "8081:80"
        environment:
            LOG_STORAGE: /var/log/web-traffic.log
        volumes:
            - logs:/var/log        

volumes:

  logs: