//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.17 at 01:37:45 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.student.com/soap/contract", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.student.soap.contract;
