//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.13 at 12:38:13 PM BST 
//


package com.student.soap.scheduleservice.contract;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.student.soap.scheduleservice.contract package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.student.soap.scheduleservice.contract
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsResponse }
     * 
     */
    public SoapCarRatingsAndCommentsResponse createSoapCarRatingsAndCommentsResponse() {
        return new SoapCarRatingsAndCommentsResponse();
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsResponse.Comments }
     * 
     */
    public SoapCarRatingsAndCommentsResponse.Comments createSoapCarRatingsAndCommentsResponseComments() {
        return new SoapCarRatingsAndCommentsResponse.Comments();
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsResponse.Comments.Comment }
     * 
     */
    public SoapCarRatingsAndCommentsResponse.Comments.Comment createSoapCarRatingsAndCommentsResponseCommentsComment() {
        return new SoapCarRatingsAndCommentsResponse.Comments.Comment();
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies }
     * 
     */
    public SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies createSoapCarRatingsAndCommentsResponseCommentsCommentReplies() {
        return new SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies();
    }

    /**
     * Create an instance of {@link SoapResponse }
     * 
     */
    public SoapResponse createSoapResponse() {
        return new SoapResponse();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link SoapAddCarPriceListRequest }
     * 
     */
    public SoapAddCarPriceListRequest createSoapAddCarPriceListRequest() {
        return new SoapAddCarPriceListRequest();
    }

    /**
     * Create an instance of {@link SoapAddPriceListRequest }
     * 
     */
    public SoapAddPriceListRequest createSoapAddPriceListRequest() {
        return new SoapAddPriceListRequest();
    }

    /**
     * Create an instance of {@link SoapAddPriceRequest }
     * 
     */
    public SoapAddPriceRequest createSoapAddPriceRequest() {
        return new SoapAddPriceRequest();
    }

    /**
     * Create an instance of {@link SoapDeleteCarPriceListRequest }
     * 
     */
    public SoapDeleteCarPriceListRequest createSoapDeleteCarPriceListRequest() {
        return new SoapDeleteCarPriceListRequest();
    }

    /**
     * Create an instance of {@link SoapDeletePriceListRequest }
     * 
     */
    public SoapDeletePriceListRequest createSoapDeletePriceListRequest() {
        return new SoapDeletePriceListRequest();
    }

    /**
     * Create an instance of {@link SoapDeletePriceRequest }
     * 
     */
    public SoapDeletePriceRequest createSoapDeletePriceRequest() {
        return new SoapDeletePriceRequest();
    }

    /**
     * Create an instance of {@link SoapCartBundleRequest }
     * 
     */
    public SoapCartBundleRequest createSoapCartBundleRequest() {
        return new SoapCartBundleRequest();
    }

    /**
     * Create an instance of {@link SoapCartUnbundleRequest }
     * 
     */
    public SoapCartUnbundleRequest createSoapCartUnbundleRequest() {
        return new SoapCartUnbundleRequest();
    }

    /**
     * Create an instance of {@link SoapCartAddCarRequest }
     * 
     */
    public SoapCartAddCarRequest createSoapCartAddCarRequest() {
        return new SoapCartAddCarRequest();
    }

    /**
     * Create an instance of {@link SoapCartRemoveCarRequest }
     * 
     */
    public SoapCartRemoveCarRequest createSoapCartRemoveCarRequest() {
        return new SoapCartRemoveCarRequest();
    }

    /**
     * Create an instance of {@link SoapCartRequest }
     * 
     */
    public SoapCartRequest createSoapCartRequest() {
        return new SoapCartRequest();
    }

    /**
     * Create an instance of {@link SoapCartResponse }
     * 
     */
    public SoapCartResponse createSoapCartResponse() {
        return new SoapCartResponse();
    }

    /**
     * Create an instance of {@link Bundle }
     * 
     */
    public Bundle createBundle() {
        return new Bundle();
    }

    /**
     * Create an instance of {@link SoapCarRatingRequest }
     * 
     */
    public SoapCarRatingRequest createSoapCarRatingRequest() {
        return new SoapCarRatingRequest();
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsRequest }
     * 
     */
    public SoapCarRatingsAndCommentsRequest createSoapCarRatingsAndCommentsRequest() {
        return new SoapCarRatingsAndCommentsRequest();
    }

    /**
     * Create an instance of {@link SoapCarRatingResponse }
     * 
     */
    public SoapCarRatingResponse createSoapCarRatingResponse() {
        return new SoapCarRatingResponse();
    }

    /**
     * Create an instance of {@link SoapCarPriceRequest }
     * 
     */
    public SoapCarPriceRequest createSoapCarPriceRequest() {
        return new SoapCarPriceRequest();
    }

    /**
     * Create an instance of {@link SoapCarPriceResponse }
     * 
     */
    public SoapCarPriceResponse createSoapCarPriceResponse() {
        return new SoapCarPriceResponse();
    }

    /**
     * Create an instance of {@link SoapCarAvailabilityRequest }
     * 
     */
    public SoapCarAvailabilityRequest createSoapCarAvailabilityRequest() {
        return new SoapCarAvailabilityRequest();
    }

    /**
     * Create an instance of {@link SoapCarAvailabilityResponse }
     * 
     */
    public SoapCarAvailabilityResponse createSoapCarAvailabilityResponse() {
        return new SoapCarAvailabilityResponse();
    }

    /**
     * Create an instance of {@link SoapCarPhysicalRequest }
     * 
     */
    public SoapCarPhysicalRequest createSoapCarPhysicalRequest() {
        return new SoapCarPhysicalRequest();
    }

    /**
     * Create an instance of {@link SoapCarPhysicalResponse }
     * 
     */
    public SoapCarPhysicalResponse createSoapCarPhysicalResponse() {
        return new SoapCarPhysicalResponse();
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies.Reply }
     * 
     */
    public SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies.Reply createSoapCarRatingsAndCommentsResponseCommentsCommentRepliesReply() {
        return new SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies.Reply();
    }

}
