--STATUS-----------------------
INSERT INTO STATUS (ID, NAME) VALUES (1,'PENDING_APPROVAL');
INSERT INTO STATUS (ID, NAME) VALUES (2,'ACTIVATED');
INSERT INTO STATUS (ID, NAME) VALUES (3,'BLOCKED');


--ROLE-------------------------
INSERT INTO ROLE (ID, NAME) VALUES (1,'BASIC');
INSERT INTO ROLE (ID, NAME) VALUES (2,'AGENT');
INSERT INTO ROLE (ID, NAME) VALUES (3,'ADMIN');

--RESOURSE TYPE----------------
INSERT INTO RESOURSE_TYPE (ID, NAME) VALUES (1, 'USER');
INSERT INTO RESOURSE_TYPE (ID, NAME) VALUES (2, 'AGENT');

--PERMISSION-------------------
INSERT INTO PERMISSION (ID, NAME) VALUES (1, 'Add Car');

--USER---------------------------
INSERT INTO USER (ID, ROLE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, STATUS_ID, EMAIL_VERIFIED, PASSWORD)
VALUES (1, 1, 'StudentFirstName', 'StudentLastName', 'student@mail.com', '021000001', 2, TRUE,
'$2a$10$iIlRkT3uRcprLxxzsagQzuiV6WCwN9Cyuu1gUCp7ACmIPzv5WxQHa');

INSERT INTO USER (ID, ROLE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, STATUS_ID, EMAIL_VERIFIED, PASSWORD)
VALUES (2, 2, 'AgentFirstName', 'AgentLastName', 'agent@mail.com', '021000002', 2, TRUE,
'$2a$10$iIlRkT3uRcprLxxzsagQzuiV6WCwN9Cyuu1gUCp7ACmIPzv5WxQHa');

INSERT INTO USER (ID, ROLE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, STATUS_ID, EMAIL_VERIFIED, PASSWORD)
VALUES (3, 3, 'AdminFirstName', 'AdminLastName', 'admin@mail.com', '021000003', 2, TRUE,
'$2a$10$iIlRkT3uRcprLxxzsagQzuiV6WCwN9Cyuu1gUCp7ACmIPzv5WxQHa');

--USER PERMISSION--------
INSERT INTO USER_PERMISSION (ID, USER_ID, PERMISSION_ID, UNIX_TIMESTAMP, RESOURSE_TYPE_ID, RESOURSE_ID)
VALUES (1, 1, 1, '1589665206', 1, null);

INSERT INTO USER_PERMISSION (ID, USER_ID, PERMISSION_ID, UNIX_TIMESTAMP, RESOURSE_TYPE_ID, RESOURSE_ID)
VALUES (2, 2, 1, '1589665206', 2, 1);