//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.13 at 10:40:08 AM BST 
//


package com.student.soap.carservice.contract;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.student.soap.carservice.contract package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.student.soap.carservice.contract
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SoapCarModelsResponse }
     * 
     */
    public SoapCarModelsResponse createSoapCarModelsResponse() {
        return new SoapCarModelsResponse();
    }

    /**
     * Create an instance of {@link SoapCarModelsResponse.CarModels }
     * 
     */
    public SoapCarModelsResponse.CarModels createSoapCarModelsResponseCarModels() {
        return new SoapCarModelsResponse.CarModels();
    }

    /**
     * Create an instance of {@link SoapResponse }
     * 
     */
    public SoapResponse createSoapResponse() {
        return new SoapResponse();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link SoapCarManufacturersRequest }
     * 
     */
    public SoapCarManufacturersRequest createSoapCarManufacturersRequest() {
        return new SoapCarManufacturersRequest();
    }

    /**
     * Create an instance of {@link SoapAllCarModelsRequest }
     * 
     */
    public SoapAllCarModelsRequest createSoapAllCarModelsRequest() {
        return new SoapAllCarModelsRequest();
    }

    /**
     * Create an instance of {@link SoapTransmissionTypesRequest }
     * 
     */
    public SoapTransmissionTypesRequest createSoapTransmissionTypesRequest() {
        return new SoapTransmissionTypesRequest();
    }

    /**
     * Create an instance of {@link SoapFuelTypesRequest }
     * 
     */
    public SoapFuelTypesRequest createSoapFuelTypesRequest() {
        return new SoapFuelTypesRequest();
    }

    /**
     * Create an instance of {@link SoapCarClassesRequest }
     * 
     */
    public SoapCarClassesRequest createSoapCarClassesRequest() {
        return new SoapCarClassesRequest();
    }

    /**
     * Create an instance of {@link SoapCarModelsByManufacturerRequest }
     * 
     */
    public SoapCarModelsByManufacturerRequest createSoapCarModelsByManufacturerRequest() {
        return new SoapCarModelsByManufacturerRequest();
    }

    /**
     * Create an instance of {@link SoapAddCarClassRequest }
     * 
     */
    public SoapAddCarClassRequest createSoapAddCarClassRequest() {
        return new SoapAddCarClassRequest();
    }

    /**
     * Create an instance of {@link SoapDeleteCarClassRequest }
     * 
     */
    public SoapDeleteCarClassRequest createSoapDeleteCarClassRequest() {
        return new SoapDeleteCarClassRequest();
    }

    /**
     * Create an instance of {@link SoapAddManufacturerRequest }
     * 
     */
    public SoapAddManufacturerRequest createSoapAddManufacturerRequest() {
        return new SoapAddManufacturerRequest();
    }

    /**
     * Create an instance of {@link SoapDeleteManufacturerRequest }
     * 
     */
    public SoapDeleteManufacturerRequest createSoapDeleteManufacturerRequest() {
        return new SoapDeleteManufacturerRequest();
    }

    /**
     * Create an instance of {@link SoapAddCarModelRequest }
     * 
     */
    public SoapAddCarModelRequest createSoapAddCarModelRequest() {
        return new SoapAddCarModelRequest();
    }

    /**
     * Create an instance of {@link SoapDeleteCarModelRequest }
     * 
     */
    public SoapDeleteCarModelRequest createSoapDeleteCarModelRequest() {
        return new SoapDeleteCarModelRequest();
    }

    /**
     * Create an instance of {@link SoapAddFuelTypeRequest }
     * 
     */
    public SoapAddFuelTypeRequest createSoapAddFuelTypeRequest() {
        return new SoapAddFuelTypeRequest();
    }

    /**
     * Create an instance of {@link SoapDeleteFuelTypeRequest }
     * 
     */
    public SoapDeleteFuelTypeRequest createSoapDeleteFuelTypeRequest() {
        return new SoapDeleteFuelTypeRequest();
    }

    /**
     * Create an instance of {@link SoapAddTransmissionTypeRequest }
     * 
     */
    public SoapAddTransmissionTypeRequest createSoapAddTransmissionTypeRequest() {
        return new SoapAddTransmissionTypeRequest();
    }

    /**
     * Create an instance of {@link SoapDeleteTransmissionTypeRequest }
     * 
     */
    public SoapDeleteTransmissionTypeRequest createSoapDeleteTransmissionTypeRequest() {
        return new SoapDeleteTransmissionTypeRequest();
    }

    /**
     * Create an instance of {@link SoapAddLocationRequest }
     * 
     */
    public SoapAddLocationRequest createSoapAddLocationRequest() {
        return new SoapAddLocationRequest();
    }

    /**
     * Create an instance of {@link SoapDeleteLocationRequest }
     * 
     */
    public SoapDeleteLocationRequest createSoapDeleteLocationRequest() {
        return new SoapDeleteLocationRequest();
    }

    /**
     * Create an instance of {@link SoapNamedObjectsResponse }
     * 
     */
    public SoapNamedObjectsResponse createSoapNamedObjectsResponse() {
        return new SoapNamedObjectsResponse();
    }

    /**
     * Create an instance of {@link NamedObject }
     * 
     */
    public NamedObject createNamedObject() {
        return new NamedObject();
    }

    /**
     * Create an instance of {@link SoapCarRequest }
     * 
     */
    public SoapCarRequest createSoapCarRequest() {
        return new SoapCarRequest();
    }

    /**
     * Create an instance of {@link SoapCarResponse }
     * 
     */
    public SoapCarResponse createSoapCarResponse() {
        return new SoapCarResponse();
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link SoapGetImageRequest }
     * 
     */
    public SoapGetImageRequest createSoapGetImageRequest() {
        return new SoapGetImageRequest();
    }

    /**
     * Create an instance of {@link SoapGetImageResponse }
     * 
     */
    public SoapGetImageResponse createSoapGetImageResponse() {
        return new SoapGetImageResponse();
    }

    /**
     * Create an instance of {@link SoapPostImageRequest }
     * 
     */
    public SoapPostImageRequest createSoapPostImageRequest() {
        return new SoapPostImageRequest();
    }

    /**
     * Create an instance of {@link SoapPostImageResponse }
     * 
     */
    public SoapPostImageResponse createSoapPostImageResponse() {
        return new SoapPostImageResponse();
    }

    /**
     * Create an instance of {@link SoapDeleteImageRequest }
     * 
     */
    public SoapDeleteImageRequest createSoapDeleteImageRequest() {
        return new SoapDeleteImageRequest();
    }

    /**
     * Create an instance of {@link SoapDeactivatePublisherRequest }
     * 
     */
    public SoapDeactivatePublisherRequest createSoapDeactivatePublisherRequest() {
        return new SoapDeactivatePublisherRequest();
    }

    /**
     * Create an instance of {@link SoapAddCarRequest }
     * 
     */
    public SoapAddCarRequest createSoapAddCarRequest() {
        return new SoapAddCarRequest();
    }

    /**
     * Create an instance of {@link SoapSearchCarsRequest }
     * 
     */
    public SoapSearchCarsRequest createSoapSearchCarsRequest() {
        return new SoapSearchCarsRequest();
    }

    /**
     * Create an instance of {@link SoapLocationsRequest }
     * 
     */
    public SoapLocationsRequest createSoapLocationsRequest() {
        return new SoapLocationsRequest();
    }

    /**
     * Create an instance of {@link SoapSearchCarsResponse }
     * 
     */
    public SoapSearchCarsResponse createSoapSearchCarsResponse() {
        return new SoapSearchCarsResponse();
    }

    /**
     * Create an instance of {@link SoapCarModelsResponse.CarModels.CarModel }
     * 
     */
    public SoapCarModelsResponse.CarModels.CarModel createSoapCarModelsResponseCarModelsCarModel() {
        return new SoapCarModelsResponse.CarModels.CarModel();
    }

}
