--LOCATION---------------------------------------------
MERGE INTO LOCATION AS target USING (SELECT 1 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (1, 'Beograd');

MERGE INTO LOCATION AS target USING (SELECT 2 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (2, 'Novi Sad');

MERGE INTO LOCATION AS target USING (SELECT 3 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (3, 'Niš');

MERGE INTO LOCATION AS target USING (SELECT 4 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (4, 'Priština');

MERGE INTO LOCATION AS target USING (SELECT 5 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (5, 'Kragujevac');

MERGE INTO LOCATION AS target USING (SELECT 6 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (6, 'Leskovac');

MERGE INTO LOCATION AS target USING (SELECT 7 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (7, 'Subotica');

MERGE INTO LOCATION AS target USING (SELECT 8 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (8, 'Zrenjanin');

MERGE INTO LOCATION AS target USING (SELECT 9 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (9, 'Pančevo');

MERGE INTO LOCATION AS target USING (SELECT 10 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (10, 'Čačak');

MERGE INTO LOCATION AS target USING (SELECT 11 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (11, 'Novi Pazar');

MERGE INTO LOCATION AS target USING (SELECT 12 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (12, 'Kraljevo');

MERGE INTO LOCATION AS target USING (SELECT 13 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (13, 'Smederevo');

MERGE INTO LOCATION AS target USING (SELECT 14 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (14, 'Valjevo');

MERGE INTO LOCATION AS target USING (SELECT 15 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (15, 'Kruševac');

MERGE INTO LOCATION AS target USING (SELECT 16 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (16, 'Vranje');

MERGE INTO LOCATION AS target USING (SELECT 17 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (17, 'Šabac');

MERGE INTO LOCATION AS target USING (SELECT 18 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (18, 'Užice');

MERGE INTO LOCATION AS target USING (SELECT 19 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (19, 'Sombor');

MERGE INTO LOCATION AS target USING (SELECT 20 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT ( ID, NAME) VALUES (20, 'Požarevac');

--PUBLISHER TYPE
MERGE INTO PUBLISHER_TYPE AS target USING (SELECT 1 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (1, 'USER');

MERGE INTO PUBLISHER_TYPE AS target USING (SELECT 2 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (2, 'AGENT');

--CAR CLASS
MERGE INTO CAR_CLASS AS target USING (SELECT 1 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (1, 'Limousine');

MERGE INTO CAR_CLASS AS target USING (SELECT 2 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (2, 'Hatchback');

MERGE INTO CAR_CLASS AS target USING (SELECT 3 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (3, 'Coupe');

MERGE INTO CAR_CLASS AS target USING (SELECT 4 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (4, 'Convertible');

MERGE INTO CAR_CLASS AS target USING (SELECT 5 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (5, 'Kombi');

--TRANSMISSION TYPE
MERGE INTO TRANSMISSION_TYPE AS target USING (SELECT 1 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (1, 'Manual');

MERGE INTO TRANSMISSION_TYPE AS target USING (SELECT 2 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (2, 'Automatic');

MERGE INTO TRANSMISSION_TYPE AS target USING (SELECT 3 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (3, 'CVT');

--FUEL TYPE
MERGE INTO FUEL_TYPE AS target USING (SELECT 1 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (1, 'Petrol');

MERGE INTO FUEL_TYPE AS target USING (SELECT 2 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (2, 'Diesel');

MERGE INTO FUEL_TYPE AS target USING (SELECT 3 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (3, 'CNG');

MERGE INTO FUEL_TYPE AS target USING (SELECT 4 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (4, 'Hybrid');

MERGE INTO FUEL_TYPE AS target USING (SELECT 5 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (5, 'Electric');

--CAR MANUFACTURER 
MERGE INTO CAR_MANUFACTURER AS target USING (SELECT 1 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (1, 'Honda');
 
MERGE INTO CAR_MANUFACTURER AS target USING (SELECT 2 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (2, 'Opel');
 
MERGE INTO CAR_MANUFACTURER AS target USING (SELECT 3 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (3, 'Ford');
 
MERGE INTO CAR_MANUFACTURER AS target USING (SELECT 4 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (4, 'Fiat');
 
MERGE INTO CAR_MANUFACTURER AS target USING (SELECT 5 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (5, 'Tesla');
 
MERGE INTO CAR_MANUFACTURER AS target USING (SELECT 6 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (6, 'BMW');
 
MERGE INTO CAR_MANUFACTURER AS target USING (SELECT 7 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (7, 'Audi');
 
MERGE INTO CAR_MANUFACTURER AS target USING (SELECT 8 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (8, 'Subaru');
 
MERGE INTO CAR_MANUFACTURER AS target USING (SELECT 9 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, NAME) VALUES (9, 'Mazda');

--CAR MODEL
--Honda 
MERGE INTO CAR_MODEL AS target USING (SELECT 1 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (1, 1, 'Civic');
 
MERGE INTO CAR_MODEL AS target USING (SELECT 2 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (2, 1, 'Accord');
--Opel
 
MERGE INTO CAR_MODEL AS target USING (SELECT 3 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (3, 2, 'Astra G');
 
MERGE INTO CAR_MODEL AS target USING (SELECT 4 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (4, 2, 'Insignia');
--Ford
 
MERGE INTO CAR_MODEL AS target USING (SELECT 5 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (5, 3, 'Focus');
 
MERGE INTO CAR_MODEL AS target USING (SELECT 6 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (6, 3, 'Fiesta');
--Fiat
 
MERGE INTO CAR_MODEL AS target USING (SELECT 7 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (7, 4, 'Panda');
 
MERGE INTO CAR_MODEL AS target USING (SELECT 8 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (8, 4, 'Stilo');
--Tesla
 
MERGE INTO CAR_MODEL AS target USING (SELECT 9 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (9, 5, 'Model 3');
 
MERGE INTO CAR_MODEL AS target USING (SELECT 10 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (10, 5, 'Model S');
--BMW
 
MERGE INTO CAR_MODEL AS target USING (SELECT 11 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (11, 6, 'I8');
 
MERGE INTO CAR_MODEL AS target USING (SELECT 12 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (12, 6, 'X7');
--Audi
 
MERGE INTO CAR_MODEL AS target USING (SELECT 13 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (13, 7, 'A6');
 
MERGE INTO CAR_MODEL AS target USING (SELECT 14 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (14, 7, 'Q5');
--Subaru
 
MERGE INTO CAR_MODEL AS target USING (SELECT 15 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (15, 8, 'Impreza');
 
MERGE INTO CAR_MODEL AS target USING (SELECT 16 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (16, 8, 'Forester');
--Mazda
 
MERGE INTO CAR_MODEL AS target USING (SELECT 17 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (17, 9, 'CX-5');
 
MERGE INTO CAR_MODEL AS target USING (SELECT 18 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, MANUFACTURER_ID, NAME) VALUES (18, 9, 'CX-9');

--CAR
--Honda 
MERGE INTO CAR AS target USING (SELECT 1 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, ACTIVE, PUBLISHER_ID, PUBLISHER_TYPE_ID, CHILD_SEATS, MILEAGE, CARCLASS_ID, MODEL_ID, FUELTYPE_ID, TRANSMISSIONTYPE_ID, LOCATION_ID) VALUES (1, TRUE, 1, 2, 1, 225000, 3, 1, 1, 1, 1);
 
MERGE INTO CAR AS target USING (SELECT 2 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, ACTIVE, PUBLISHER_ID, PUBLISHER_TYPE_ID, CHILD_SEATS, MILEAGE, CARCLASS_ID, MODEL_ID, FUELTYPE_ID, TRANSMISSIONTYPE_ID, LOCATION_ID) VALUES (2, TRUE, 1, 2, 0, 110000, 1, 1, 2, 2, 1);
 
MERGE INTO CAR AS target USING (SELECT 3 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, ACTIVE, PUBLISHER_ID, PUBLISHER_TYPE_ID, CHILD_SEATS, MILEAGE, CARCLASS_ID, MODEL_ID, FUELTYPE_ID, TRANSMISSIONTYPE_ID, LOCATION_ID) VALUES (3, TRUE, 1, 2, 1, 219000, 2, 2, 3, 1, 1);
 
MERGE INTO CAR AS target USING (SELECT 4 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, ACTIVE, PUBLISHER_ID, PUBLISHER_TYPE_ID, CHILD_SEATS, MILEAGE, CARCLASS_ID, MODEL_ID, FUELTYPE_ID, TRANSMISSIONTYPE_ID, LOCATION_ID) VALUES (4, TRUE, 1, 2, 0, 110700, 1, 2, 1, 3, 1);
 
MERGE INTO CAR AS target USING (SELECT 5 as ID) AS source ON target.ID=source.ID
WHEN NOT MATCHED THEN INSERT (ID, ACTIVE, PUBLISHER_ID, PUBLISHER_TYPE_ID, CHILD_SEATS, MILEAGE, CARCLASS_ID, MODEL_ID, FUELTYPE_ID, TRANSMISSIONTYPE_ID, LOCATION_ID) VALUES (5, TRUE, 1, 1, 0, 27100, 1, 2, 2, 2, 1);