//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 11:11:24 AM CEST 
//


package com.student.soap.contract.scheduleservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.student.soap.contract.scheduleservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.student.soap.contract.scheduleservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SoapResponse }
     * 
     */
    public SoapResponse createSoapResponse() {
        return new SoapResponse();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link SoapAddCarPriceListRequest }
     * 
     */
    public SoapAddCarPriceListRequest createSoapAddCarPriceListRequest() {
        return new SoapAddCarPriceListRequest();
    }

    /**
     * Create an instance of {@link SoapAddPriceListRequest }
     * 
     */
    public SoapAddPriceListRequest createSoapAddPriceListRequest() {
        return new SoapAddPriceListRequest();
    }

    /**
     * Create an instance of {@link SoapAddPriceRequest }
     * 
     */
    public SoapAddPriceRequest createSoapAddPriceRequest() {
        return new SoapAddPriceRequest();
    }

    /**
     * Create an instance of {@link SoapDeleteCarPriceListRequest }
     * 
     */
    public SoapDeleteCarPriceListRequest createSoapDeleteCarPriceListRequest() {
        return new SoapDeleteCarPriceListRequest();
    }

    /**
     * Create an instance of {@link SoapDeletePriceListRequest }
     * 
     */
    public SoapDeletePriceListRequest createSoapDeletePriceListRequest() {
        return new SoapDeletePriceListRequest();
    }

    /**
     * Create an instance of {@link SoapDeletePriceRequest }
     * 
     */
    public SoapDeletePriceRequest createSoapDeletePriceRequest() {
        return new SoapDeletePriceRequest();
    }

    /**
     * Create an instance of {@link SoapCartBundleRequest }
     * 
     */
    public SoapCartBundleRequest createSoapCartBundleRequest() {
        return new SoapCartBundleRequest();
    }

    /**
     * Create an instance of {@link SoapCartUnbundleRequest }
     * 
     */
    public SoapCartUnbundleRequest createSoapCartUnbundleRequest() {
        return new SoapCartUnbundleRequest();
    }

    /**
     * Create an instance of {@link SoapPendingCommentsRequest }
     * 
     */
    public SoapPendingCommentsRequest createSoapPendingCommentsRequest() {
        return new SoapPendingCommentsRequest();
    }

    /**
     * Create an instance of {@link SoapPendingCommentsResponse }
     * 
     */
    public SoapPendingCommentsResponse createSoapPendingCommentsResponse() {
        return new SoapPendingCommentsResponse();
    }

    /**
     * Create an instance of {@link Correspondence }
     * 
     */
    public Correspondence createCorrespondence() {
        return new Correspondence();
    }

    /**
     * Create an instance of {@link SoapApproveCommentRequest }
     * 
     */
    public SoapApproveCommentRequest createSoapApproveCommentRequest() {
        return new SoapApproveCommentRequest();
    }

    /**
     * Create an instance of {@link SoapRejectCommentRequest }
     * 
     */
    public SoapRejectCommentRequest createSoapRejectCommentRequest() {
        return new SoapRejectCommentRequest();
    }

    /**
     * Create an instance of {@link SoapCartAddCarRequest }
     * 
     */
    public SoapCartAddCarRequest createSoapCartAddCarRequest() {
        return new SoapCartAddCarRequest();
    }

    /**
     * Create an instance of {@link SoapCartRemoveCarRequest }
     * 
     */
    public SoapCartRemoveCarRequest createSoapCartRemoveCarRequest() {
        return new SoapCartRemoveCarRequest();
    }

    /**
     * Create an instance of {@link SoapCartRequest }
     * 
     */
    public SoapCartRequest createSoapCartRequest() {
        return new SoapCartRequest();
    }

    /**
     * Create an instance of {@link SoapBundlesResponse }
     * 
     */
    public SoapBundlesResponse createSoapBundlesResponse() {
        return new SoapBundlesResponse();
    }

    /**
     * Create an instance of {@link Bundle }
     * 
     */
    public Bundle createBundle() {
        return new Bundle();
    }

    /**
     * Create an instance of {@link SoapAddRatingRequest }
     * 
     */
    public SoapAddRatingRequest createSoapAddRatingRequest() {
        return new SoapAddRatingRequest();
    }

    /**
     * Create an instance of {@link SoapPendingRatingRequest }
     * 
     */
    public SoapPendingRatingRequest createSoapPendingRatingRequest() {
        return new SoapPendingRatingRequest();
    }

    /**
     * Create an instance of {@link SoapPendingRatingResponse }
     * 
     */
    public SoapPendingRatingResponse createSoapPendingRatingResponse() {
        return new SoapPendingRatingResponse();
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link SoapCarRatingRequest }
     * 
     */
    public SoapCarRatingRequest createSoapCarRatingRequest() {
        return new SoapCarRatingRequest();
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsRequest }
     * 
     */
    public SoapCarRatingsAndCommentsRequest createSoapCarRatingsAndCommentsRequest() {
        return new SoapCarRatingsAndCommentsRequest();
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsResponse }
     * 
     */
    public SoapCarRatingsAndCommentsResponse createSoapCarRatingsAndCommentsResponse() {
        return new SoapCarRatingsAndCommentsResponse();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link SoapCarRatingResponse }
     * 
     */
    public SoapCarRatingResponse createSoapCarRatingResponse() {
        return new SoapCarRatingResponse();
    }

    /**
     * Create an instance of {@link SoapCarPriceRequest }
     * 
     */
    public SoapCarPriceRequest createSoapCarPriceRequest() {
        return new SoapCarPriceRequest();
    }

    /**
     * Create an instance of {@link SoapCarPriceResponse }
     * 
     */
    public SoapCarPriceResponse createSoapCarPriceResponse() {
        return new SoapCarPriceResponse();
    }

    /**
     * Create an instance of {@link SoapCarAvailabilityRequest }
     * 
     */
    public SoapCarAvailabilityRequest createSoapCarAvailabilityRequest() {
        return new SoapCarAvailabilityRequest();
    }

    /**
     * Create an instance of {@link SoapCarAvailabilityResponse }
     * 
     */
    public SoapCarAvailabilityResponse createSoapCarAvailabilityResponse() {
        return new SoapCarAvailabilityResponse();
    }

    /**
     * Create an instance of {@link SoapCarPhysicalRequest }
     * 
     */
    public SoapCarPhysicalRequest createSoapCarPhysicalRequest() {
        return new SoapCarPhysicalRequest();
    }

    /**
     * Create an instance of {@link SoapCarPhysicalResponse }
     * 
     */
    public SoapCarPhysicalResponse createSoapCarPhysicalResponse() {
        return new SoapCarPhysicalResponse();
    }

    /**
     * Create an instance of {@link SoapReserveRequest }
     * 
     */
    public SoapReserveRequest createSoapReserveRequest() {
        return new SoapReserveRequest();
    }

    /**
     * Create an instance of {@link SoapRejectReservationRequest }
     * 
     */
    public SoapRejectReservationRequest createSoapRejectReservationRequest() {
        return new SoapRejectReservationRequest();
    }

    /**
     * Create an instance of {@link SoapCancelReservationRequest }
     * 
     */
    public SoapCancelReservationRequest createSoapCancelReservationRequest() {
        return new SoapCancelReservationRequest();
    }

    /**
     * Create an instance of {@link SoapApproveReservationRequest }
     * 
     */
    public SoapApproveReservationRequest createSoapApproveReservationRequest() {
        return new SoapApproveReservationRequest();
    }

    /**
     * Create an instance of {@link SoapUserReservationsRequest }
     * 
     */
    public SoapUserReservationsRequest createSoapUserReservationsRequest() {
        return new SoapUserReservationsRequest();
    }

    /**
     * Create an instance of {@link SoapPublisherReservationsRequest }
     * 
     */
    public SoapPublisherReservationsRequest createSoapPublisherReservationsRequest() {
        return new SoapPublisherReservationsRequest();
    }

    /**
     * Create an instance of {@link SoapMessagesRequest }
     * 
     */
    public SoapMessagesRequest createSoapMessagesRequest() {
        return new SoapMessagesRequest();
    }

    /**
     * Create an instance of {@link SoapAddMessageRequest }
     * 
     */
    public SoapAddMessageRequest createSoapAddMessageRequest() {
        return new SoapAddMessageRequest();
    }

    /**
     * Create an instance of {@link SoapMessagesResponse }
     * 
     */
    public SoapMessagesResponse createSoapMessagesResponse() {
        return new SoapMessagesResponse();
    }

}
