//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
// Generated on: 2020.06.04 at 07:13:11 PM CEST 
=======
// Generated on: 2020.06.03 at 11:04:09 PM CEST 
>>>>>>> 90ae7a7f0050ecc99b4b2d909c7a43c5b16043ab
//


package com.student.scheduleservice.soap.contract;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.student.scheduleservice.soap.contract package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.student.scheduleservice.soap.contract
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsResponse }
     * 
     */
    public SoapCarRatingsAndCommentsResponse createSoapCarRatingsAndCommentsResponse() {
        return new SoapCarRatingsAndCommentsResponse();
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsResponse.Comments }
     * 
     */
    public SoapCarRatingsAndCommentsResponse.Comments createSoapCarRatingsAndCommentsResponseComments() {
        return new SoapCarRatingsAndCommentsResponse.Comments();
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsResponse.Comments.Comment }
     * 
     */
    public SoapCarRatingsAndCommentsResponse.Comments.Comment createSoapCarRatingsAndCommentsResponseCommentsComment() {
        return new SoapCarRatingsAndCommentsResponse.Comments.Comment();
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies }
     * 
     */
    public SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies createSoapCarRatingsAndCommentsResponseCommentsCommentReplies() {
        return new SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies();
    }

    /**
     * Create an instance of {@link SoapCarRatingRequest }
     * 
     */
    public SoapCarRatingRequest createSoapCarRatingRequest() {
        return new SoapCarRatingRequest();
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsRequest }
     * 
     */
    public SoapCarRatingsAndCommentsRequest createSoapCarRatingsAndCommentsRequest() {
        return new SoapCarRatingsAndCommentsRequest();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link SoapCarRatingResponse }
     * 
     */
    public SoapCarRatingResponse createSoapCarRatingResponse() {
        return new SoapCarRatingResponse();
    }

    /**
     * Create an instance of {@link SoapCarPriceRequest }
     * 
     */
    public SoapCarPriceRequest createSoapCarPriceRequest() {
        return new SoapCarPriceRequest();
    }

    /**
     * Create an instance of {@link SoapCarPriceResponse }
     * 
     */
    public SoapCarPriceResponse createSoapCarPriceResponse() {
        return new SoapCarPriceResponse();
    }

    /**
     * Create an instance of {@link SoapCarAvailabilityRequest }
     * 
     */
    public SoapCarAvailabilityRequest createSoapCarAvailabilityRequest() {
        return new SoapCarAvailabilityRequest();
    }

    /**
     * Create an instance of {@link SoapCarAvailabilityResponse }
     * 
     */
    public SoapCarAvailabilityResponse createSoapCarAvailabilityResponse() {
        return new SoapCarAvailabilityResponse();
<<<<<<< HEAD
    }

    /**
     * Create an instance of {@link SoapCarPhysicalRequest }
     * 
     */
    public SoapCarPhysicalRequest createSoapCarPhysicalRequest() {
        return new SoapCarPhysicalRequest();
    }

    /**
     * Create an instance of {@link SoapCarPhysicalResponse }
     * 
     */
    public SoapCarPhysicalResponse createSoapCarPhysicalResponse() {
        return new SoapCarPhysicalResponse();
=======
>>>>>>> 90ae7a7f0050ecc99b4b2d909c7a43c5b16043ab
    }

    /**
     * Create an instance of {@link SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies.Reply }
     * 
     */
    public SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies.Reply createSoapCarRatingsAndCommentsResponseCommentsCommentRepliesReply() {
        return new SoapCarRatingsAndCommentsResponse.Comments.Comment.Replies.Reply();
    }

}
